#!/bin/sh
#
# Simple stunnel init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

STUNNELPORT=8443
EXEC=/usr/local/bin/stunnel
CLIEXEC=/usr/local/bin/stunnel

PIDFILE=/var/run/stunnel_${STUNNELPORT}.pid
CONF="/etc/stunnel/${STUNNELPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, stunnel is already running or crashed"
        else
                echo "Starting stunnel server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, stunnel is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
				kill $PID
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for stunnel to shutdown ..."
                    sleep 1
                done
				rm -f $PIDFILE
                echo "stunnel stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
